Repository auth0/node-auth0, pull requests merged in 2020-10, with the labels that each got.

#542 Bumps Rest-Facade Dependencies
  package.json
  yarn.lock
Labels: CH: Fixed

#538 [SDK-1975] Use exponential backoff rather than rate limit headers
  package.json
  src/RetryRestClient.js
  test/retry-rest-client.tests.js
  yarn.lock
Labels: CH: Changed

#543 Provide headers on mgmt token fetch
  src/management/ManagementTokenProvider.js
  test/management/management-token-provider.tests.js
Labels: CH: Added, tiny
