Repository auth0/node-auth0, pull requests merged in 2020-09, with the labels that each got.

#528 Adding call to invalidate all remembered browsers.
  src/management/UsersManager.js
  src/management/index.js
  test/management/management-client.tests.js
  test/management/users.tests.js
Labels: CH: Added

#533 Adding support for prompts and custom texts
  src/management/PromptsManager.js
  src/management/index.js
  test/management/management-client.tests.js
  test/management/prompts.tests.js
Labels: CH: Added

#534 Update jwks-rsa dependency to avoid DeprecationWarning Buffer()
  package.json
  yarn.lock
Labels: CH: Changed

#535 Update dependencies
  package.json
  yarn.lock
Labels: CH: Changed

#519 Merge pull request #510 from ademartini/ESD-7544-redux
  src/management/JobsManager.js
  src/management/TicketsManager.js
Labels: CH: Added, DO NOT MERGE, tiny
