Repository auth0/node-auth0, pull requests merged in 2020-07, with the labels that each got.

#507 Sanitize Headers on Errors
  src/Auth0RestClient.js
  src/errors.js
  test/auth0-rest-client.tests.js
  test/errors.tests.js
Labels: CH: Security, enhancement, medium

#510 Adding docs for secondary and federated identity email verification
  src/management/JobsManager.js
  src/management/TicketsManager.js
Labels: CH: Changed

#515 Use [REDACTED] instead of [SANITIZED] when cleaning errors
  src/errors.js
  test/auth0-rest-client.tests.js
  test/errors.tests.js
Labels: CH: Changed, tiny

#514 Document user_id parameter for getDeviceCredentials API
  src/management/DeviceCredentialsManager.js
  src/management/index.js
Labels: documentation, tiny

#516 Revert "Merge pull request #510 from ademartini/ESD-7544-redux"
  src/management/JobsManager.js
  src/management/TicketsManager.js
Labels: tiny
