Repository auth0/node-auth0, pull requests merged in 2020-06, with the labels that each got.

#495 Bump codecov - npm audit fix
  package.json
  yarn.lock
Labels: tiny

#498 Fixes dependency vulnerabilities from webpack
  yarn.lock
Labels: CH: Security, tiny

#501 feat(guardian): support policies, selected-provider, message-types methods [MFA-310]
  src/management/GuardianManager.js
  src/management/index.js
  test/management/guardian.tests.js
  test/management/management-client.tests.js
Labels: CH: Added

#503 feat(migrations): adds migrations manager
  src/management/MigrationsManager.js
  src/management/index.js
  test/management/migrations.tests.js
Labels: CH: Added

#502 Added deleteUserByEmail to ConnectionsManager
  src/management/ConnectionsManager.js
  test/management/connections.tests.js
Labels: CH: Added
