Repository auth0/node-auth0, pull requests merged in 2021-07, with the labels that each got.

#629 [ESD-14303] Remove invalid testTrigger in ActionsManager
  src/management/ActionsManager.js
  test/management/actions.tests.js
Labels: CH: Fixed

#634 [SDK-2666] Update endpoint methods to document allowance of 'from' and 'take' checkpoint pagination parameters
  src/management/LogsManager.js
  src/management/OrganizationsManager.js
  src/management/RolesManager.js
Labels: documentation, review:tiny

#628 Mark package as side effect free
  package.json
Labels: enhancement

#640 Fix docs for rate limit default maxRetries
  src/RetryRestClient.js
Labels: documentation, review:tiny
