Repository auth0/node-auth0, pull requests merged in 2021-03, with the labels that each got.

#591 Allow passwordless SMS code verification to use token endpoint
  src/auth/index.js
  test/auth/authentication-client.tests.js
Labels: CH: Added, review:small

#597 Org idtoken validation support
  src/auth/OAUthWithIDTokenValidation.js
  src/auth/OAuthAuthenticator.js
  src/auth/idToken.js
  src/auth/index.js
  test/idToken.tests.js
Labels: CH: Added

#598 Add type check to org_id
  src/auth/idToken.js
Labels: review:tiny

#592 feat(orgs): Support Organization feature
  src/management/JobsManager.js
  src/management/OrganizationsManager.js
  src/management/TicketsManager.js
  src/management/UsersManager.js
  src/management/index.js
  test/management/organizations.tests.js
  test/management/users.tests.js
Labels: CH: Added

#599 Doc fixes
  src/auth/OAuthAuthenticator.js
  src/auth/PasswordlessAuthenticator.js
  src/auth/TokensManager.js
  src/auth/UsersManager.js
  src/auth/index.js
Labels: review:tiny
