Repository auth0/node-auth0, pull requests merged in 2021-01, with the labels that each got.

#561 Expose assignUsersToRole to ManagementClient
  src/management/index.js
Labels: CH: Added

#563 Expose getJobErrors to management client
  src/management/index.js
Labels: CH: Fixed

#562 Fix passing a custom User-Agent to Axios.
  docs/auth_index.js.html
  docs/management_index.js.html
  src/auth/index.js
  src/management/index.js
  test/auth/authentication-client.tests.js
  test/management/management-client.tests.js
  test/management/management-token-provider.tests.js
  webpack.config.js
Labels: CH: Fixed

#577 Additional options on getByEmail [SDK-2268]
  src/management/UsersManager.js
  src/management/index.js
  test/management/users.tests.js
Labels: CH: Added, review:small
