Repository auth0/node-auth0, pull requests merged in 2021-09, with the labels that each got.

#651 Use the new release automation solution
  .shiprc
  package.json
  scripts/exec.js
  scripts/jsdocs.js
  scripts/release.js
Labels: review:tiny

#642 Fix undefined tokenProvider when access token is provided.
  src/management/index.js
Labels: CH: Fixed

#659 Update JSDocs for Organizations
  src/management/OrganizationsManager.js
Labels: documentation, review:small

#660 Update docs for sendEmailVerification
  src/management/index.js
Labels: documentation, review:tiny

#661 Add forwardedFor to passwordGrant
  src/auth/index.js
Labels: documentation, review:tiny
