Repository auth0/node-auth0, pull requests merged in 2023-01, with the labels that each got.

#761 [SDK-3856] Add `client_assertion` to authenticate clients
  .jshintrc
  package.json
  src/auth/OAuthAuthenticator.js
  src/auth/PasswordlessAuthenticator.js
  src/auth/TokensManager.js
  src/auth/clientAuthentication.js
  src/auth/index.js
  src/management/ManagementTokenProvider.js
  src/management/index.js
  test/auth/oauth.tests.js
  test/client-authentication.tests.js
  test/constants.js
  yarn.lock
Labels: CH: Added, review:medium

#772 chore: Bump `yarn.lock` dependencies
  yarn.lock
Labels: dependencies, review:tiny

#774 [SDK-3868] Add support for managing client credentials
  src/management/ClientCredentialsManager.js
  src/management/index.js
  test/management/client-credentials.tests.js
Labels: review:small

#776 bump-jwks-rsa
  package.json
  yarn.lock
Labels: tiny
